source 'https://rubygems.org'

# Test dependencies follow

gem 'gaq', path: '../..'
gem 'rails', '~> 3.1.0'
gem 'rspec-rails', '~> 2.12.0'
gem 'capybara', '~> 2.0.0'
gem 'terminal-notifier-guard'
gem 'rb-fsevent' # used by guard for watching
gem 'guard-rspec'
gem 'debugger'
